apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: nodejs-pipelinerun-
spec:
  serviceAccountName: docker-login
  pipelineRef:
    name: nodejs-pipeline
  params:
    - name: IMAGE
      value: docker.io/koustavs18/nodejs-app
    - name: TAG
      value: latest
  workspaces:
    - name: linked-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi